// Generated by scripts/generate-map-previews.ts. Do not edit by hand.
export const routePreviewPaths = {
  "valle-delle-ferriere": {
    compact: "/route-previews/valle-delle-ferriere-compact-6efe13dc3481.webp",
    wide: "/route-previews/valle-delle-ferriere-wide-4462fedfe09e.webp",
  },
  "torre-dello-ziro": {
    compact: "/route-previews/torre-dello-ziro-compact-213734edfafb.webp",
    wide: "/route-previews/torre-dello-ziro-wide-b9a6f7e13c67.webp",
  },
  "path-of-the-gods": {
    compact: "/route-previews/path-of-the-gods-compact-eea6e46fc334.webp",
    wide: "/route-previews/path-of-the-gods-wide-14931e4573a8.webp",
  },
  "the-lemon-path": {
    compact: "/route-previews/the-lemon-path-compact-0a7e2722c8df.webp",
    wide: "/route-previews/the-lemon-path-wide-1d3715666747.webp",
  },
} as const;
