import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { routeAssets, type StaticPreviewSize } from "../src/lib/place-routes";

const OUTPUT_DIR = path.join(process.cwd(), "public", "route-previews");
const MANIFEST_PATH = path.join(process.cwd(), "src", "lib", "route-previews.generated.ts");
const QUALITY = 55;
const DIMENSIONS: Record<StaticPreviewSize, string> = {
  compact: "600x450",
  wide: "900x675",
};
const GENERATED_FILE_PATTERN = /^[a-z0-9-]+-(compact|wide)-[a-f0-9]{12}\.webp$/;

const formatCoordinate = ([lon, lat]: [number, number]): string =>
  `${lon.toFixed(5)},${lat.toFixed(5)}`;

function getMapboxUrl(
  route: (typeof routeAssets)[number],
  size: StaticPreviewSize,
  token: string,
): string {
  const encodedPolyline = encodeURIComponent(route.staticPreview.polyline);
  const overlays = [
    `path-10+3f1d0d-0.32(${encodedPolyline})`,
    `path-5+f97316-1(${encodedPolyline})`,
    `pin-s-a+166534(${formatCoordinate(route.staticPreview.start)})`,
    `pin-s-b+b91c1c(${formatCoordinate(route.staticPreview.end)})`,
  ].join(",");

  return `https://api.mapbox.com/styles/v1/mapbox/outdoors-v12/static/${overlays}/auto/${DIMENSIONS[size]}?padding=48&access_token=${encodeURIComponent(token)}`;
}

async function downloadPreview(
  route: (typeof routeAssets)[number],
  size: StaticPreviewSize,
  token: string,
): Promise<Buffer> {
  const response = await fetch(getMapboxUrl(route, size, token));
  if (!response.ok) {
    throw new Error(`Mapbox returned ${response.status} for ${route.slug} (${size})`);
  }

  return sharp(Buffer.from(await response.arrayBuffer()))
    .webp({ quality: QUALITY, effort: 6 })
    .toBuffer();
}

function renderManifest(paths: Record<string, Record<StaticPreviewSize, string>>): string {
  const routes = Object.entries(paths)
    .map(([slug, sizes]) => `  "${slug}": {\n    compact: "${sizes.compact}",\n    wide: "${sizes.wide}",\n  },`)
    .join("\n");

  return `// Generated by scripts/generate-map-previews.ts. Do not edit by hand.\nexport const routePreviewPaths = {\n${routes}\n} as const;\n`;
}

async function main() {
  const token = process.env.NEXT_PUBLIC_MAPBOX_TOKEN;
  if (!token) {
    throw new Error("NEXT_PUBLIC_MAPBOX_TOKEN is required to generate map previews");
  }

  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  const manifest: Record<string, Record<StaticPreviewSize, string>> = {};
  const generatedFiles = new Set<string>();

  for (const route of routeAssets) {
    const sizes = {} as Record<StaticPreviewSize, string>;
    for (const size of ["compact", "wide"] as const) {
      const output = await downloadPreview(route, size, token);
      const hash = createHash("sha256").update(output).digest("hex").slice(0, 12);
      const filename = `${route.slug}-${size}-${hash}.webp`;
      await fs.writeFile(path.join(OUTPUT_DIR, filename), output);
      generatedFiles.add(filename);
      sizes[size] = `/route-previews/${filename}`;
      console.log(`Generated ${filename} (${output.byteLength} bytes)`);
    }
    manifest[route.slug] = sizes;
  }

  await fs.writeFile(MANIFEST_PATH, renderManifest(manifest), "utf8");

  for (const filename of await fs.readdir(OUTPUT_DIR)) {
    if (GENERATED_FILE_PATTERN.test(filename) && !generatedFiles.has(filename)) {
      await fs.unlink(path.join(OUTPUT_DIR, filename));
    }
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
