import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const GUIDE_DIR = path.join(ROOT, "public", "guide-webp");
const OUTPUT = path.join(ROOT, "src", "lib", "place-gallery.generated.ts");

/**
 * Scans public/guide-webp/ for subdirectories. Any subdirectory is treated as a
 * multi-photo gallery for the place whose slug matches the directory name.
 * Files are sorted alphabetically (01.webp, 02.webp, … → predictable ordering).
 *
 * The flat, top-level images stay owned by src/lib/place-images.ts — this script
 * only generates the supplementary multi-photo data.
 */
const collect = (): Record<string, string[]> => {
    const galleries: Record<string, string[]> = {};
    if (!fs.existsSync(GUIDE_DIR)) return galleries;
    const entries = fs.readdirSync(GUIDE_DIR, { withFileTypes: true });
    for (const entry of entries) {
        if (!entry.isDirectory()) continue;
        const slug = entry.name;
        const dirPath = path.join(GUIDE_DIR, slug);
        const files = fs
            .readdirSync(dirPath)
            .filter((f) => /\.(webp|jpe?g|png|avif)$/i.test(f))
            .sort();
        if (files.length === 0) continue;
        galleries[slug] = files.map((f) => `/guide-webp/${slug}/${f}`);
    }
    return galleries;
};

const galleries = collect();
const banner = "// This file is auto-generated by scripts/generate-place-gallery.mts — do not edit by hand.\n\n";
const body = `export const placeGalleries: Record<string, readonly string[]> = ${JSON.stringify(
    galleries,
    null,
    2,
)} as const;\n`;

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, banner + body, "utf8");

const count = Object.keys(galleries).length;
console.log(`[place-gallery] wrote ${count} galleries → ${path.relative(ROOT, OUTPUT)}`);
