import sharp from "sharp";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PUBLIC = path.join(ROOT, "public");
const OUTPUT = path.join(ROOT, "src", "lib", "blur-data.generated.ts");

async function generateBlurDataURL(imagePath: string): Promise<string> {
  const buffer = await sharp(imagePath)
    .resize(8, 8, { fit: "cover" })
    .jpeg({ quality: 40 })
    .toBuffer();
  return `data:image/jpeg;base64,${buffer.toString("base64")}`;
}

async function main() {
  const blurMap: Record<string, string> = {};

  // Process guide-webp directory
  const guideDir = path.join(PUBLIC, "guide-webp");
  const guideFiles = fs.readdirSync(guideDir).filter((f) => f.endsWith(".webp"));

  for (const file of guideFiles) {
    const publicPath = `/guide-webp/${file}`;
    const fullPath = path.join(guideDir, file);
    blurMap[publicPath] = await generateBlurDataURL(fullPath);
    console.log(`  Generated blur: ${publicPath}`);
  }

  // Process hero image
  const heroPath = path.join(PUBLIC, "images", "hero.webp");
  if (fs.existsSync(heroPath)) {
    blurMap["/images/hero.webp"] = await generateBlurDataURL(heroPath);
    console.log("  Generated blur: /images/hero.webp");
  }

  // Process author photo
  const gregsPath = path.join(PUBLIC, "images", "gregs-masked.png");
  if (fs.existsSync(gregsPath)) {
    blurMap["/images/gregs-masked.png"] = await generateBlurDataURL(gregsPath);
    console.log("  Generated blur: /images/gregs-masked.png");
  }

  // Write TypeScript output
  const lines = Object.entries(blurMap)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => `  "${key}": "${value}",`)
    .join("\n");

  const content = `// Auto-generated by scripts/generate-blur-data.mts
// Do not edit manually. Re-run: npm run generate:blur
export const blurDataMap: Record<string, string> = {
${lines}
};

export function getBlurDataURL(src: string): string | undefined {
  return blurDataMap[src];
}
`;

  fs.writeFileSync(OUTPUT, content, "utf-8");
  console.log(`\nWrote ${Object.keys(blurMap).length} blur entries to ${OUTPUT}`);
}

main().catch(console.error);
